### ISSUE TITLE
CLI help text cleanup

### ISSUE THREAD

**Issue by LCVcode** [LCVcode/jockey#19]
The following corrections need to be made to the CLI help text:

- [ ] Replace outdated `!=` filter code with the correct `^=`
- [ ] Update filter examples to demonstrate all available filter modes
- [ ] Change the tool description to be more descriptive
- [ ] Find an alternate way to display object type aliases 

In the below sample of the current help text, you can see an example of the abbreviation list that needs to be changed.  Ideally, this would show the most readable version of each object type (`{charms, applications, units, machines, hostnames, ips}`).

```bash
python3 jockey.py --help                                     
usage: jockey.py [-h] [--refresh] [-f FILE]
                 [{charms,charm,c,app,apps,application,applications,a,units,unit,u,machines,machine,m,address,addresses,ips,ip,i,hostnames,hostname,host,hosts,h}] [filters [filters ...]]

Jockey - All your Juju objects at your fingertips.

positional arguments:
  {charms,charm,c,app,apps,application,applications,a,units,unit,u,machines,machine,m,address,addresses,ips,ip,i,hostnames,hostname,host,hosts,h}
<truncated>
```

**Comment by johnlettman** [comment]
Would you be open to exploring the use of [click](https://click.palletsprojects.com/en/8.1.x/) and [rich](https://rich.readthedocs.io/en/stable/introduction.html)?


![image](https://github.com/LCVcode/jockey/assets/20583294/9d6005b8-0be6-409c-a29c-ab6e921c9766)

**Comment by LCVcode** [comment]
Those seem like cool options, thank you.  I will definitely look into `click` as an alternative to `argparse`.  Personally, I am not as excited about enhancing colors myself with `rich`, but I would be excited for someone else to do it.  I will open a follow-up issue for that purpose after I made some changes to the CLI.

**Comment by LCVcode** [comment]
I am currently working on replacing `argparse` with `click`.  I will likely change multiple files names as part of this work.
