### ISSUE TITLE
Investigate using rich package to add color to Jockey outputs

### ISSUE THREAD

**Issue by LCVcode** [LCVcode/jockey#20]
We should look into using [rich](https://rich.readthedocs.io/en/stable/introduction.html) as a way to spice up Jockey outputs to improve readability and generally make them more interesting/fun.  I would like to see some example outputs from people who feel that outputs should be colored in a particular way.  

**Any work done here must not affect Jockey's ability to be piped into other commands.**  Pipeline compatibility is a first principle for this project.  

Blocked by #19

**Comment by johnlettman** [comment]
> Any work done here must not affect Jockey's ability to be piped into other commands. Pipeline compatibility is a first principle for this project.

I hard agree. To approach this, we will want to use the `isatty` call (e.g., `sys.stdin.isatty()`).
Likewise, it does appear `rich` will make [a best effort to do this automatically](https://rich.readthedocs.io/en/stable/console.html#terminal-detection).

**Comment by LCVcode** [comment]
I think beautifying the output would be an excellent feature when humans are the final reader.  One question that comes to my mind is how will this interact which Jockey outputs are set as a variable, which I would expect to see done quite frequently in playbooks and hopefully generally out in the wild.  

`UNITS=$(jockey units)` need to not be beautified for the sake of scripting.

**Comment by johnlettman** [comment]
I created a small demo of the auto-detection to confirm our requirements here:
```python
from rich.console import Console

console = Console()
print(f"color_system:     {console.color_system}")
print(f"is_terminal:      {console.is_terminal}")
print(f"is_dumb_terminal: {console.is_dumb_terminal}")
```

Using this, I can confirm that all of our expectations are covered.

#### Standard invocation (expect color)
##### Command
```bash
python3 ./rich-test.py 
```
##### Output
```
color_system:     truecolor
is_terminal:      True
is_dumb_terminal: False
```

#### Variable encapsulation (expect no color)
##### Command
```bash
test="$(python3 ./rich-test.py)"; echo "${test}"
```

##### Output
```
color_system:     None
is_terminal:      False
is_dumb_terminal: False
```

#### Piped `stdout` (expect no color)
##### Command
(note: on my system, `cat` is rebound to `rcat`)
```bash
python3 ./rich-test.py | rcat
```

##### Output
```
color_system:     None
is_terminal:      False
is_dumb_terminal: False
```
