### ISSUE TITLE
Move status keeper into jockey file

### ISSUE THREAD

**Issue by LCVcode** [LCVcode/jockey#25]
Currently, `status_keeper.py` handles the caching of the local Juju status.  This file needs to be merged into `jockey.py`, as there is not a good reason for it to be separated out.

**Comment by johnlettman** [comment]
This may not be necessary if #6 is closed, given that the entire application would be bundled as a static executable. The one-file program requirement would become nil and you could expand out to several files and modules for organization purposes.

**Comment by LCVcode** [comment]
I agree that #6 resolved this.

This issue is now stale and I am closing it.
