### ISSUE TITLE
Feature: `juju-jockey` CLI testing

### ISSUE THREAD

**Issue by LCVcode** [LCVcode/jockey#49]
## Problem
Current testing does not includes calls to `juju-jockey`.  Ideally, these tests commands would be run in the context of a snap, just as a real user would.  

## Proposed Feature
Add tests which call `juju-jockey` in a variety of contexts.  A minimum coverage list would be:
- `juju-jockey info`
- Querying units with various filters
- Querying machines with various filters
- Querying across models (in the near future)

**Comment by johnlettman** [comment]
100% +1 here. This can catch regressions in the syntax and obvious errors that unit tests may not catch due to them loading functions in through the library interface.
