### ISSUE TITLE
mypy check not working

### ISSUE THREAD

**Issue by enriqueqs** [LCVcode/jockey#56]
## Describe the Bug
Cannot run mypy
`poetry run mypy src
`

## Steps to Reproduce
1. Follow installation instructions
2. Perform the following check:
```
# Lint with mypy
poetry run mypy src
```

## Expected Behavior
it should pass the test

## Screenshots/Logs
<img width="817" alt="Screenshot 2024-09-02 at 15 34 55" src="https://github.com/user-attachments/assets/b02cf25b-0ae8-4a34-86ae-08e03ab6f793">

## Environment
- **Operating system:**  macOS 14.3.1
- **Python version:** Python 3.12.5
- **Juju version:**  -

## Additional Context
*(Optional) Any other details?*

**Comment by johnlettman** [comment]
I can confirm it's cooked in `master`. The changes in #47 seem to fix this; however, the types need work.
