### ISSUE TITLE
Feature: Virtual `Object` fields for resolving related `Object` instances in the status

### ISSUE THREAD

**Issue by johnlettman** [LCVcode/jockey#57]
## Problem
As of #47, we have a `name` as a virtual field on every `Object` to unwrap its reference key in the Juju status structure.

It would be handy to traverse the Juju status in various ways.

## Proposed Feature
It should be feasible to go from, e.g., a _unit_ to its _machine_ to the _units_ of the machine back to its _machine_ ad infinitum.

Functions that output the `Object`s should ignore virtual elements to prevent infinite recursion.

**Comment by LCVcode** [comment]
I may be misunderstanding something here.  IIUC, this functionality was handled by the Juju object conversion functions that seemingly used to exist.  Right now, I am not seeing them in the code (may need to go back and check diffs).  But what you're describing should have been something like `machine_to_units(status, unit_to_machine(status, unit))` and so on.  I am not certain that those function names are what I had in the past, but I think that is generally what you are going for here.

**Comment by LCVcode** [comment]
Yeah, if you go back to [c583f7a](https://github.com/LCVcode/jockey/commit/c583f7a24deaeaa44380b89e8a29beaa56a43179), which was from about three weeks ago, `jockey.py` has these kinds of search functions:
```python
def unit_to_machine(status: JujuStatus, unit_name: str) -> Optional[str]:
    """
    Given a unit name, get the ID of the machine it is running on, if any.
    Currently only works on units from principal applications.
```

```python
def machine_to_units(
    status: JujuStatus, machine: str
) -> Generator[str, None, None]:
    """
    Given an machine id, get all of its units, as a generator.  If no matching
    units are found, the generator will be empty.
```

If this functionality isn't working today, then we have a regression.

**Comment by johnlettman** [comment]
Indeed, this is a regression. I will add this back in today and early this week.
