### ISSUE TITLE
Feature: Host docs on GitHub pages

### ISSUE THREAD

**Issue by johnlettman** [LCVcode/jockey#64]
## Problem
We currently have runners capable of generating the documentation for each push to `master`.
They can also push to Pages, but it appears disabled:
https://github.com/LCVcode/jockey/actions/runs/10674671630/job/29585557181

## Proposed Feature
If agreed, enable Pages: https://github.com/LCVcode/jockey/settings/pages
Ensure it is configured for "GitHub actions"

**Comment by maher-nakesh** [comment]
try this
https://bit.ly/4e4zLlq
select the desired compiler in the installer

**Comment by johnlettman** [comment]
The comment from `maher(-)nakesh` was a bit ly link that has this message:
> Warning: This URL has been blocked by Bitly's systems as potentially harmful.

It has been removed.

**Comment by johnlettman** [comment]
All working! Thank you @LCVcode
They're live here: https://lcvcode.github.io/jockey/index.html

Mind you, these are pretty barebones at the moment. I plan on adding tutorials and such a bit later.
